format = """
[░▒▓](#a3aed2)\
[](bg:#268bd2 fg:#a3aed2)\
$directory\
[](fg:#268db2 bg:#CB4B16)\
$git_branch\
$git_status\
[](fg:#CB4B16 bg:#859900)\
$nodejs\
[](fg:#859900 bg:#B58900)\
${custom.ddev}\
[ ](fg:#B58900)\
$character"""

[directory]
style = "fg:#EEE8D5 bg:#268db2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "   "
"Music" = "   "
"Pictures" = "   "

[git_branch]
symbol = ""
style = "bg:#CB4B16"
format = '[[ $symbol $branch ](fg:#EEE8D5 bg:#CB4B16)]($style)'

[git_status]
style = "bg:#CB4B16"
format = '[[($all_status$ahead_behind )](fg:#EEE8D5 bg:#CB4B16)]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:#859900"
format = '[[ $symbol ($version) ](fg:#EEE8D5 bg:#859900)]($style)'

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[❯](bold red) '

[line_break]
disabled = true 

[custom.ddev]
description = "Shows the currently active ddev project as we should really only be running 1 at a time"
command = "docker ps | awk 'NR==1 {offset=index($0,\"NAMES\")};NR>1{print substr($0,offset)}' | sort -f | grep '\\-web' | sed 's/.*\\-\\(.*\\)\\-.*/\\1/' | head -1"
symbol = " "
when = "[[ -d .ddev ]]"
format = '[[ $symbol $output ](fg:#EEE8D5 bg:#B58900)]($style)'
