palette = "catppuccin_latte"
format = """
[░▒▓](#35a77c)\
[](bg:#3a94c5 fg:#35a77c)\
$directory\
[](fg:#3a94c5 bg:#f57d26)\
$git_branch\
$git_status\
[](fg:#f57d26 bg:#8da101)\
$nodejs\
[](fg:#8da101 bg:#dfa000)\
${custom.ddev}\
[ ](fg:#dfa000)\
$character"""

[directory]
style = "fg:#EEE8D5 bg:#3a94c5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "   "
"Music" = "   "
"Pictures" = "   "

[git_branch]
symbol = ""
style = "bg:#f57d26"
format = '[[ $symbol $branch ](fg:#EEE8D5 bg:#f57d26)]($style)'

[git_status]
style = "bg:#f57d26"
format = '[[($all_status$ahead_behind )](fg:#EEE8D5 bg:#f57d26)]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:#8da101"
format = '[[ $symbol ($version) ](fg:#EEE8D5 bg:#8da101)]($style)'

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[❯](bold red) '

[line_break]
disabled = true

[custom.ddev]
description = "Shows the currently active ddev project as we should really only be running 1 at a time"
command = "docker ps | awk 'NR==1 {offset=index($0,\"NAMES\")};NR>1{print substr($0,offset)}' | sort -f | grep '\\-web' | sed 's/.*\\-\\(.*\\)\\-.*/\\1/' | head -1"
symbol = " "
when = "[[ -d .ddev ]]"
format = '[[ $symbol $output ](fg:#EEE8D5 bg:#dfa000)]($style)'

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
