# == Ignore Globs ==
# A list of globs to ignore when listing.
ignore-globs:
  - .git
  - .git/*
  - vendor
  - vendor/*
  - cpresources
  - cpresources/*
  - storage
  - storage/*
  - node_modules
  - node_modules/*
